version: "3"
services:
  service1:
    build:
      context: ./service
    ports:
      - 8001:5001
    environment:
      NAME: "Service1"
  service2:
    build:
      context: ./service
    ports:
      - 8002:5001
    environment:
      NAME: "Service2"
